[package]
name = "server"
version = "0.1.0"
edition = "2024"

[dependencies]
axum = { version = "0.8.9", features = ["macros"] }
axum-extra = { version = "0.12.6", features = ["typed-header"] }
axum-range = "1.0.0"
common-utils = { path = "../common-utils/" }
mime = "0.3.17"
tokio = { version = "1.53.1", features = ["net", "rt"] }
