#!/usr/bin/lua5.4
if #arg ~= 2 then
  error("Invalid number of arguments")
end

local MARKER = "<!-- Generated by scripts/generate-sitmap.lua, DO NOT MODIFY -->"
function openOutput(name)
  if not name then
    return io.stdout
  end
  
  local f<close> = io.open(name, "r")
  
  if f then
    local marker = f:read()
    if marker and marker ~= "<?xml version=\"1.0\" encoding=\"UTF-8\"?>" then
      marker = f:read()
      if marker and marker ~= MARKER then
        return nil
      end
    end
    
    f:close()
  end
  
  return assert(io.open(name, "w+"))
end

local DIR_TO_INDEX<const> = arg[1]
local FULL_URL_TO_DIR<const> = arg[2]
local replace_path<const> = "^"..DIR_TO_INDEX:gsub("([^%w])", "%%%1")
local EXTRA_SITEMAP_MATCH = "sitemap[.][-A-Za-z0-9_$#\"\'@]+[.]xml"

local CRAWLER_FILES<const> = io.popen(string.format("find %q -mindepth 1 -maxdepth 1 -type f", DIR_TO_INDEX))
local CRAWLER_DIRS<const> = io.popen(string.format("find %q -mindepth 1 -maxdepth 1 -type d", DIR_TO_INDEX))

local OUTPUT_FILE = openOutput(arg[1].."/sitemap.xml")
local OUTPUT_FILE_FOR_URLSET<close> = openOutput(arg[1].."/sitemap-url.xml")
if OUTPUT_FILE == nil then
  -- The sitemap file was manually made, do nothing other than crawling into deeper dirs
  while true do
    local line = CRAWLER_DIRS:read()
    if not line then
      break
    end
    
    local is_sitemap = line:match(EXTRA_SITEMAP_MATCH) ~= nil
    local url = line:gsub(replace_path, FULL_URL_TO_DIR)
    
    os.execute(("scripts/generate-sitemap.lua %q %q"):format(line, url, line.."/sitemap.xml"))
  end
  return
end

function writeLine(str)
  OUTPUT_FILE:write(str)
  OUTPUT_FILE:write("\n")
end

writeLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>")
writeLine(MARKER)
writeLine("<sitemapindex xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">")
writeLine("  <sitemap>")
writeLine("    <loc>"..FULL_URL_TO_DIR.."/sitemap-url.xml</loc>")
writeLine("  </sitemap>")

while true do
  local line = CRAWLER_DIRS:read()
  if not line then
    break
  end
  
  local path = line:gsub(replace_path, "")
  local url = FULL_URL_TO_DIR..path
  
  writeLine("  <sitemap>")
  writeLine("    <loc>"..url.."/sitemap.xml</loc>")
  writeLine("  </sitemap>")
  
  os.execute(("scripts/generate-sitemap.lua %q %q"):format(line, url))
end
writeLine("</sitemapindex>")

OUTPUT_FILE:close()
OUTPUT_FILE = OUTPUT_FILE_FOR_URLSET

if OUTPUT_FILE == nil then
  error("sitemap-url.xml cannot be overriden")
end

-- https://developers.google.com/search/docs/crawling-indexing/sitemaps/build-sitemap?hl=en#xml
writeLine("<?xml version=\"1.0\" encoding=\"UTF-8\"?>")
writeLine(MARKER)
writeLine("<urlset xmlns=\"http://www.sitemaps.org/schemas/sitemap/0.9\">")

while true do
  local line = CRAWLER_FILES:read()
  if not line then
    break
  end
  
  -- Only include ourself
  if not line:match("[/]sitemap[.]xml$") and not line:match("[/]sitemap-url[.]xml$") then
    local is_sitemap = line:match("[/]"..EXTRA_SITEMAP_MATCH.."$") ~= nil
      
    if is_sitemap then
        writeLine("  <sitemap>")
      writeLine("    <loc>"..line:gsub(replace_path, FULL_URL_TO_DIR).."</loc>")
      writeLine("  </sitemap>")
    else
      writeLine("  <url>")
      writeLine("    <loc>"..line:gsub(replace_path, FULL_URL_TO_DIR).."</loc>")
      writeLine("  </url>")
    end
  end
end
writeLine("</urlset>")



