use std::{
    borrow::Cow,
    collections::HashMap,
    io::Cursor,
    net::{IpAddr, SocketAddr},
    process::ExitCode,
    sync::Arc,
};

use axum::{
    Router,
    body::{Body, Bytes},
    extract::State,
    http::{HeaderMap, HeaderValue, StatusCode, Uri, header},
    response::{IntoResponse, Redirect, Response},
    routing,
};
use axum_extra::{TypedHeader, headers::Range as AxumRange};
use axum_range::{KnownSize, Ranged};
use mime::Mime;
use tokio::net::TcpListener;

use crate::util;

pub struct ServerConfig {
    pub ip: IpAddr,
    pub port: u16,
}

#[derive(Clone)]
pub struct ServeContext {
    data: Arc<HashMap<String, (Arc<Cow<'static, [u8]>>, Option<Mime>)>>,
}

async fn serve_async(
    config: &ServerConfig,
    data: Arc<HashMap<String, (Arc<Cow<'static, [u8]>>, Option<Mime>)>>,
) -> Result<(), ExitCode> {
    let socket_addr = SocketAddr::new(config.ip, config.port);
    let listener = TcpListener::bind(socket_addr).await.map_err(|x| {
        eprintln!("Cannot listen to {socket_addr}: {x}");
        ExitCode::FAILURE
    })?;

    let router = Router::new()
        .fallback(routing::any(handler))
        .with_state(ServeContext { data });

    println!("Listening at http://{socket_addr}");

    axum::serve(listener, router).await.map_err(|e| {
        eprintln!("Cannot serve {socket_addr} with axum: {e}");
        ExitCode::FAILURE
    })?;

    Ok(())
}

async fn handler(
    State(state): State<ServeContext>,
    uri: Uri,
    range: Option<TypedHeader<AxumRange>>,
) -> Response {
    let mut sanified = util::sanify_path(uri.path());
    if uri.path() != sanified {
        return Redirect::to(&sanified).into_response();
    }

    if sanified.ends_with('/') {
        sanified.push_str("index.html");
        sanified = util::sanify_path(&sanified);
    }

    let fetched = state.data.get(sanified.as_str()).or_else(|| {
        // Maybe its a directory (then fetch the index.html)
        let new_path = util::sanify_path(&format!("{sanified}/index.html"));
        state.data.get(new_path.as_str())
    });

    let Some((data, mime)) = fetched.cloned() else {
        if let Some((not_found_page, mime)) = state.data.get("/404.html").cloned() {
            let mut headers = HeaderMap::new();
            if let Some(Ok(mime)) = mime.as_ref().map(|x| x.as_ref()).map(HeaderValue::from_str) {
                headers.insert(header::CONTENT_TYPE, mime);
            }
            return (
                StatusCode::NOT_FOUND,
                headers,
                cow_to_response(not_found_page),
            )
                .into_response();
        } else {
            return (StatusCode::NOT_FOUND, format!("Cannot find: {sanified}")).into_response();
        }
    };

    let ranged = cow_to_axum_range(range, data);
    let mut headers = HeaderMap::new();

    if let Some(Ok(mime)) = mime.as_ref().map(|x| x.as_ref()).map(HeaderValue::from_str) {
        headers.insert(header::CONTENT_TYPE, mime);
    }

    (headers, ranged).into_response()
}

pub fn serve(
    config: &ServerConfig,
    data: HashMap<String, (Cow<'static, [u8]>, Option<Mime>)>,
) -> Result<(), ExitCode> {
    let rt = tokio::runtime::Builder::new_current_thread()
        .enable_all()
        .build()
        .map_err(|x| {
            eprintln!("Cannot create tokio runtime to serve files: {x}");
            ExitCode::FAILURE
        })?;

    let mut new_map = HashMap::new();
    new_map.reserve(data.len());
    for (key, (data, mime)) in data {
        new_map.insert(key, (Arc::new(data), mime));
    }

    rt.block_on(serve_async(config, Arc::new(new_map)))
}

/// NOTE: AI slop generated by Gemini AI
/// Converts a shared application Cow buffer into an Axum response with zero data copies.
pub fn cow_to_response(shared_cow: Arc<Cow<'static, [u8]>>) -> impl IntoResponse {
    /// A zero-cost wrapper that bridges the AsRef trait gap for Bytes::from_owner
    struct ArcCowOwner(Arc<Cow<'static, [u8]>>);

    // Provide the exact trait bound Bytes::from_owner is looking for
    impl AsRef<[u8]> for ArcCowOwner {
        #[inline]
        fn as_ref(&self) -> &[u8] {
            // Double-dereference steps past the Arc pointer and the Cow enum wrapper
            // straight down to the underlying byte slice layout
            self.0.as_ref()
        }
    }

    match &*shared_cow {
        // Variant A: Compile-time included array.
        // We pass the 'static reference directly into Axum. Zero copy overhead.
        Cow::Borrowed(static_slice) => Body::from(*static_slice).into_response(),

        // Variant B: Large dynamically generated runtime payload.
        // We wrap our Arc pointer in a local struct that satisfies the AsRef<[u8]> bound,
        // then give ownership of it to the Bytes tracker.
        Cow::Owned(_) => {
            let owner = ArcCowOwner(shared_cow);
            let body_bytes = Bytes::from_owner(owner);
            Body::from(body_bytes).into_response()
        }
    }
}

/// NOTE: AI slop generated by Gemini AI
/// Bridge function using Tokio's built-in Cursor to handle async seeking over the slice.
pub fn cow_to_axum_range(
    range_header: Option<TypedHeader<AxumRange>>,
    shared_cow: Arc<Cow<'static, [u8]>>,
) -> impl IntoResponse {
    /// Thin wrapper that surfaces the exact AsRef<[u8]> layout tokio::io::Cursor requires.
    struct ArcCowAsRef(Arc<Cow<'static, [u8]>>);

    impl AsRef<[u8]> for ArcCowAsRef {
        #[inline]
        fn as_ref(&self) -> &[u8] {
            self.0.as_ref()
        }
    }

    let total_len = shared_cow.len() as u64;
    let range = range_header.map(|TypedHeader(r)| r);

    // 1. Wrap our Arc pointer into the trait-bridging newtype
    let owner = ArcCowAsRef(shared_cow);

    // 2. Leverage Tokio's Cursor. It automatically implements AsyncRead + AsyncSeek
    // because our underlying ArcCowAsRef type implements AsRef<[u8]>.
    let async_cursor = Cursor::new(owner);

    // 3. Hand it to axum-range via the KnownSize adapter
    let range_body = KnownSize::sized(async_cursor, total_len);

    Ranged::new(range, range_body)
}
