on:
  push:
    branches: [ "main" ]

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v7
      
      - name: "Install nightly Rust toolchain"
        uses: dtolnay/rust-toolchain@1.97.1
      
      - name: "Enable caching on Rust stuffs"
        uses: Swatinem/rust-cache@v2
      
      - name: Build the website!
        # Run my Rust based site generator, which is orchestrated
        # by make
        run: |
          make root="https://foxieflakey.github.io" all
      
      - name: Upload to GitHub pages
        uses: actions/upload-pages-artifact@v5
        with:
          path: output/web
  
  deploy:
    runs-on: ubuntu-latest
    needs: build
    # Permission for GITHUB_TOKEN
    # to allow deploy to GitHub pages
    permissions:
      pages: write
      id-token: write
    
    # Only one deploy can run at any time
    concurrency:
      group: "pages"
      cancel-in-progress: true
    steps:
      - name: Deploy the pages
        id: deployment
        uses: actions/deploy-pages@v5
